### ISSUE TITLE
Undocumented Easypost APIs

### ISSUE THREAD

**Issue by sameerkumar18** [EasyPost/easypost-python#101]
What's a good way to extend Easypost python wrapper to support undocumented APIs like `/v2/fedex_registrations` and `v2/carrier_accounts/register` ?
We're aware of calling the endpoints directly with packages like requests, but for maintaining our code design, is it possible to extend the wrapper to support new API resources?

Thanks!

**Comment by Justintime50** [comment]
Hey @sameerkumar18, this is a great request! A few of our other libraries have PR's in progress to add this functionality. We welcome PR's if you'd like to contribute! These endpoints are certainly something to consider.

Until the functionality is added to the client library, you're correct - requests would be a great alternative.

**Comment by sameerkumar18** [comment]
Sure @Justintime50 
I'll give it a shot and update in a few days :)

**Comment by sameerkumar18** [comment]
@Justintime50 Can you take a look at #109 
Please suggest some improvements, if any. Also can you please help me with the failing tests?
Thanks! :D

**Comment by LoganSimonsen** [comment]
Just a note, FedEx CSP registration should no be possible via `v2/carrier_accounts/register` eliminating the need to deal with `/v2/fedex_registrations`

**Comment by Justintime50** [comment]
See #109 for additional details on why this was closed.
