### ISSUE TITLE
Shipment refund request method is not clear

### ISSUE THREAD

**Issue by askabelin** [EasyPost/easypost-python#105]
Hi. [The documentation](https://www.easypost.com/docs/api#refund-a-shipment) says that a shipment can be refunded using POST request.
However the library [does GET request](https://github.com/EasyPost/easypost-python/blob/master/easypost/__init__.py#L737).

Is it documentation or library bug? Or am I missing something?

**Comment by Justintime50** [comment]
Hey @askabelin, nice catch! This will technically work with GET as there are no params; however, to clarify I've submitted a PR. It should be POST.
