### ISSUE TITLE
Transliteration of non-roman text

### ISSUE THREAD

**Issue by Sultan91** [EasyPost/easypost-python#120]
Hello, do you know if easypost support auto-translation (transliteration) from non-roman to Latin alphabet as it was mentioned in their [blog](https://www.easypost.com/blog/2013-05-20-foreign-language-support)?

**Comment by Roguelazer** [comment]
I'm pretty sure that that hasn't been the case in general for many years. However, many of our carriers do correctly support unicode on labels now... If you have questions about non-ascii support for a specific carrier, please drop us a line at support@easypost.com.
