### ISSUE TITLE
Shipment.create error message with no details

### ISSUE THREAD

**Issue by timmyGr** [EasyPost/easypost-python#133]
Currently attempting to create a shipment using the [one call buy example](https://www.easypost.com/docs/api/python#shipments-one-call-buy-codesample). The API will return an error message of `easypost.Error: Missing required data to get rates.` with no details.

I've attempted a few things with no luck. 

Current call:

```
        shipment = easypost.Shipment.create(
            carrier_accounts={"0": "ca_5dbee8b1e03f436da263aab45175d1a1"},
            service="NextDayAir",
            to_address=to_address,
            from_address=from_address,
            parcel=parcel
        )
```

We've been trying multiple ways. We will get the same error message if we passed the addresses & parcel data in as a dictionary or if we pass the return of `Parcel.create()` and `Address.create()`

**Comment by Justintime50** [comment]
Hey @timmyGr, it looks like you are trying to buy a `UPS` service level with your `USPS` account. Please ensure when creating shipments that you are using services that belong to the right carrier account. If you have additional questions, our support team is a great resources for items like this - they can be reached at support@easypost.com.

Best of luck!

**Comment by timmyGr** [comment]
@Justintime50 

That's what is displayed in the documentation. Using USPS services returns the same result.

```
       shipment = easypost.Shipment.create(
            carrier_accounts={"0": "ca_5dbee8b1e03f436da263aab45175d1a1"},
            service="LargeParcel",
            to_address=to_address,
            from_address=from_address,
            parcel=parcel
        )
```

```
easypost.Error: Missing required data to get rates.
```

**Comment by Justintime50** [comment]
The examples are correct; however, they assume that the `carrier_account` and `service` are compatible. I'm unable to see the data you're passing in your address and parcel objects. If you write into our support team and provide them the shipment id, they should be able to identify the missing required data.
