### ISSUE TITLE
Error Handling Around Customs Items Not Exposing Proper Message

### ISSUE THREAD

**Issue by Justintime50** [EasyPost/easypost-python#134]
# Summary

This will need some additional investigation; but it appears that when creating a custom item with a description that is longer than the max field length (~250 characters), the Python CL is returning an unhelpful `Wrong parameter type` error. In reality, it should be returning a message stating the max field length was exceeded or something along those lines. This info should be getting returned from the API but may not be getting exposed via this library.

## Acceptance Criteria

- [ ] Investigate why the `Wrong parameter type` error is occurring
- [ ] Investigate if this error occurs for other objects/fields or is only for this one field customs_item['description']
- [ ] Create a PR to fix the error handling to properly return the message

## Additional Info

<img width="1010" alt="Screen Shot 2021-09-07 at 1 28 06 PM" src="https://user-images.githubusercontent.com/39606064/132408298-a3e6cddc-e858-4548-ab31-dc4536aa9354.png">

A typical error response should look something like:

```python
{"error":{"code":"PARAMETER.INVALID_TYPE","message":"Wrong parameter type.","errors":[{"field":"weight","message":"must be a float"}]}}
```

**Comment by jchen293** [comment]
The same error was thrown for the `quantity` field in the custom item object.

**Comment by jchen293** [comment]
It's also happening in other objects as well. I believe here is the [code](https://github.com/EasyPost/easypost-python/blob/master/easypost/__init__.py#L328-L331) that is causing the issue. We are only displaying full error message when the exception is AttributeError. I have the PR in draft but ran into an issue with one of the unit tests.

**Comment by Justintime50** [comment]
After looking into this, it appears that we were only exposing the `message` field when we raised an error when really there was an additional `code` and `errors` fields that were helpful to determine the true identity of an error. @jchen293 put up a PR to address this; however, it's a breaking change since it no longer unfurls the `message` key automatically and instead the user will be returned the full JSON error including the message field. This is a breaking change and will need a major version bump.

**Comment by Justintime50** [comment]
After doing some internal testing, the default behavior of printing the `error` is to only print the `message` field; however, you could easily instead print the `error.http_body` and get the entire message. There are ways to work with the whole message then at that point. Closing as invalid.
