### ISSUE TITLE
[Bug]: Looking for easypost.beta

### ISSUE THREAD

**Issue by amunchet** [EasyPost/easypost-python#189]
### Software Version

7.1.0

### Language Version

Python 3.10

### Operating System

Docker (Linux)

### What happened?

1. Running a new instance of CI/CD with tests that had previously passed.
2. Received the below error (appears to be looking for `easypost.beta`)

### What was expected?

No error.

### Sample Code

```python3
`import easypost`
```

### Relevant logs

```sh
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
shipping/tests/test_easypost.py:14: in <module>
    from shipping import easypost_client as ep
shipping/easypost_client.py:10: in <module>
    import easypost
/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/easypost/__init__.py:1: in <module>
    import easypost.beta
E   ModuleNotFoundError: No module named 'easypost.beta'
```

**Comment by Justintime50** [comment]
Thanks for reporting this. It appears our packaging process didn't account for this new module. You can either pin `v7.0.0` or we'll be releasing a patch within the next hour.

**Comment by amunchet** [comment]
Yup, patching 7.0.0 worked out fine.  That'll hold me over until the fix.  Thanks!

**Comment by Justintime50** [comment]
You should now be able to upgrade via https://github.com/EasyPost/easypost-python/releases/tag/v7.1.1 as this issue has been patched. Thanks again for reporting it!
