### ISSUE TITLE
Request: Subclassed Exceptions

### ISSUE THREAD

**Issue by rblakemesser** [EasyPost/easypost-python#22]
When writing tests around the easypost API, it would be helpful to be able to catch exceptions based on their subclasses instead of having a megaexception class and having to parse the message string.

Here's a snippet from our code base:

```
    except easypost.Error as e:
        # Is it a connection problem?
        if u'error communicating with EasyPost' in e.message:
            log.exception(e)
            rate = fallback_rate
        else:
            raise
```

This is slightly terrifying because our business logic has to depend on parsing error message strings, which could change across versions of your python bindings. We work around this with a unit test that literally reads the easypost code for the version and error message strings, but subclassed exceptions would be a nicer pattern.

**Comment by att14** [comment]
You should be able to use `Error.http_status` to get a better idea of what is going on. If `http_status` is `None` something bad happened and should be reported to us.

**Comment by rblakemesser** [comment]
Good to know-- thanks for the tip!
