### ISSUE TITLE
[Bug]: trouble using tax_identifiers on each shipment of an order. 

### ISSUE THREAD

**Issue by LoganSimonsen** [EasyPost/easypost-python#248]
### Software Version

EasyPost/v2 PythonClient/6.0.1  

### Language Version

Python/3.10.8

### Operating System

OS/Linux OSVersion/5.10.133+ OSArch/x86_64 Implementation/CPython

### What happened?

We are having trouble trying to figure out how to pass in tax_identifiers within an order. We verified we are using python client versions after 6.0.0, which is when tax_identifier support was implemented. If tax_identifiers do work in Python with Orders, can we get a code example? The goal is to have tax identifiers nested within each shipment object (in the shipments array) of an order.

### What was expected?

We should be able to pass in tax_identifiers inline on each shipment when creating an order, similar to this code example on the official API docs https://www.easypost.com/docs/api/python#create-an-order

### Sample Code

```python3
[a.keys() for a in data["order"]["shipments"]]
> [dict_keys(['parcel', 'carrier_accounts', 'options', 'customs_info', 'tax_identifiers'])]
```
this is getting covered into JSON and sent to the EasyPost API in this format:

```
{"order":{"to_address":{"name":"redacted redacted","company":null,"phone":"redacted","email":"[redacted@redacted.co.uk](mailto:redacted@redacted.co.uk)","street1":"redacted","street2":"redacted","city":"redacted","state":null,"zip":"redacted redacted","country":"redacted","residential":false},"from_address":{"name":"redacted redacted","company":null,"phone":"redacted","email":null,"street1":"redacted redacted Ave","street2":null,"city":"Tallmadge","state":"redacted","zip":"redacted-1431","country":"US","residential":false},"shipments":[{"parcel":{"weight":6.1},"carrier_accounts":["redacted"],"options":{"print_custom_1":"redacted","print_custom_2":"redacted","machinable":null,"label_size":"4x6","label_format":"PNG","incoterm":"CPT"},"customs_info":{"eel_pfc":null,"contents_type":"merchandise","contents_explanation":"redacted redacted redacted redacted","customs_certify":true,"non_delivery_option":"return","customs_items":[{"description":"3 redacted redacted","quantity":1,"value":20,"weight":6.0,"hs_tariff_number":"redacted","origin_country":"US","code":"redacted"}]},"tax_identifiers":[{"entity":"SENDER","tax_id":"redacted","tax_id_type":"VAT","issuing_country":"GB"}]}],"is_return":false,"carrier_accounts":
[{"id":"redacted"}]},"format":"json","controller":"orders","action":"create","version_prefix":"v2"}```
```

### Relevant logs
[Link](https://kibana.easypo.net/goto/413ede637966801ac7aa7ec6d14cb56e)

**Comment by Justintime50** [comment]
Hey @LoganSimonsen ,

We have examples for how to do this on a shipment, though to your point we don't detail this for orders. As with anything though, you should be able to pass those keys if they are correctly nested:

```python
import os

import easypost


easypost.api_key = os.getenv("EASYPOST_API_KEY")

order = easypost.Order.create(
    to_address={"id": "adr_..."},
    from_address={"id": "adr_..."},
    shipments=[
        {
            "parcel": {
                "predefined_package": "FedExBox",
                "weight": 10.2,
            },
           "tax_identifiers": { ... }
        },
        {
            "parcel": {
                "predefined_package": "FedExBox",
                "weight": 17.5,
            },
           "tax_identifiers": { ... }
        },
    ],
)

print(order)
```

Alternatively, you could create the orders beforehand with `tax_identifiers` associated and then pass an array of shipment IDs instead:

```python
    # partial snippet
    shipments=[
        {
            "id": "shp_123..."
        },
        {
            "id": "shp_456..."
        },
    ],
```

Let me know if this helps.
