### ISSUE TITLE
[Bug]: Problem Getting a report that was previously created.

### ISSUE THREAD

**Issue by LoganSimonsen** [EasyPost/easypost-python#283]
### Software Version

7.7.0

### Language Version

Python 3

### Operating System

Mac OS Ventura

### What happened?

1. When using the example found at https://www.easypost.com/docs/api/python#retrieve-a-report I am getting the error message "requested resource not found" error message. 
2. After some investigation with EasyPost, it appears that the request URL is being formatted incorrectly. It should be formatted like `/reports/:type/:id` but the actual request is coming through like `/reports/:id`. 
3. We either need a way to pull a report by id alone or we need to know how to declare the report type when requesting an already generated report.

### What was expected?

report shprep_e1c52c006216482fb84435696e204f15 should have been retrieved

### Sample Code

```python3
import os

import easypost

easypost.api_key = "redacted"

report = easypost.Report.retrieve("shprep_e1c52c006216482fb84435696e204f15")

print(report)
```

### Relevant logs

```
{"error":{"code":"NOT_FOUND","message":"The requested resource could not be found.","errors":[]}}
```

**Comment by Justintime50** [comment]
Hey @LoganSimonsen thanks for reporting this! Our API had a temporary issue with resolving URLs for retrieving reports and has since been patched. Please give your request another try and let us know if you need help with anything else.
