### ISSUE TITLE
[Feat]: Upgrade Guide

### ISSUE THREAD

**Issue by rSimonBatt** [EasyPost/easypost-python#308]
### Feature Request Is New

- [X] I have verified that the requested feature does not already exist or has not already been requested.

### Description of the feature

Doing my due diligence to pass something along from a support ticket:

>Please ignore the first question about regenerate_rates. I see in the docs that we can no longer just call shipment.regenerate_rates() but instead have to use client.shipment.regenrate_rates(). Just a suggestion here: it would be extremely helpful if that change had been specifically documented in the upgrade guide.

Have a lovely day.

**Comment by Justintime50** [comment]
Hey @rSimonBatt, thanks for the feedback! Although not explicitly called out for that function, that is detailed in our upgrade guide generally in this section: https://github.com/EasyPost/easypost-python/blob/master/UPGRADE_GUIDE.md#80-easypostclient

Note how it mentions that all functions are now static and must be called against a service and client. Hope that helps!
