### ISSUE TITLE
[Bug]: `ShipmentService.regenerate_rates` has incorrect return value type

### ISSUE THREAD

**Issue by bradydean** [EasyPost/easypost-python#317]
### Software Version

v9.0.0

### Language Version

3.12

### Operating System

Fedora

### What happened?

The return value type of `ShipmentService.regenerate_rates` is incorrect. It is typed as a `Shipment`, but the Easypost API returns a payload of

```json
{
  "rates": [
    ...
  ]
}
```

### What was expected?

The return value should be correctly typed to reflect the rates payload returned by the API.

**Comment by Justintime50** [comment]
Thanks for reporting this @bradydean! I've put up a PR for this, we'll try to get it out in the next day or two.
