### ISSUE TITLE
Error when passing unicode

### ISSUE THREAD

**Issue by sineo** [EasyPost/easypost-python#32]
Using this as my to address:
 "to_address": {
    "city": "Toronto", 
    "company": null, 
    "country": "CA", 
    "email": null, 
    "name": "R\xf5ger Hos\xe8in", 
    "phone": "5555555555", 
    "state": "ON", 
    "street1": "636 King Street West", 
    "street2": "", 
    "zip": "M5V1M7"
  }

I get the following error returned to me:
"messages": [
    {
      "api_key": "WFvVSAc8vIBZbtzgGn6f7Q", 
      "carrier": "Purolator", 
      "message": "XML request is malformed.", 
      "type": "rate_error"
    }
  ]

If I force the name to be a string, it works just fine except that the unicode characters don't translate over to Easypost, it shows as that string above. 

Any ideas?

**Comment by gsinkin** [comment]
Hi,

I can reproduce the issue. This appears to be Purolator specific. It looks like the Purolator API is not friendly with unicode.

I can ping their dev team and get more precise response. In the meantime, check out unidecode (https://pypi.python.org/pypi/Unidecode). 

Thanks,

Gabe

**Comment by sineo** [comment]
Thanks. You're absolutely right. It seems that Purolator only supports French and English, however those characters were Swedish.
I'll close this out as it's not an issue with your library.
