### ISSUE TITLE
Enter a host to ping: 

### ISSUE THREAD

**Issue by tejastank** [EasyPost/easypost-python#33]
Enter a host to ping: 

When use 

import easypost
import urllib3
urllib3.disable_warnings()
easypost.api_key = 'API_KEY'

# create address
address = easypost.Address.create(
    company="EasyPost",
    street1="118 2nd St",
    street2="4th Fl",
    city="San Francisco",
    state="CA",
    zip="94105",
    phone="415-456-7890"
)

verified_address = address.verify()

print(verified_address)

Getting ping message, what's solution ?

**Comment by k-funk** [comment]
Everything seems to be fine on this end. What do you mean by "getting ping message"? Not sure where the error is.

Also, please post your python & easypost versions.

**Comment by att14** [comment]
This doesn't appear to be an issue with our library and the code provided does not reproduce any issue. Closing.
