### ISSUE TITLE
[Bug]: EasyPost SDK Crash`'int' object has no attribute 'split'`

### ISSUE THREAD

**Issue by kcharwood** [EasyPost/easypost-python#349]
### Software Version

9.2.0

### Language Version

3.11.3

### Operating System

Linux

### What happened?

In the last hour, we have started getting crashers on this [line](https://github.com/EasyPost/easypost-python/blob/ff68dc0fb8270cf2e7f0b53b7414f2cb3e37f52d/easypost/easypost_object.py#L70) when creating new trackers using the SDK.

I don't have much more debugging information at the moment. We've been using this code path for a year+ now with Fedex and no issues.

### What was expected?

No Crash.

### Sample Code

```python3
tracker = self.client.tracker.create(
                tracking_code=tracking_code,
                carrier=carrier.value if carrier else None
)
```

**Comment by nwithan8** [comment]
Thanks for letting us know! A quick look through the code and it seems most likely the bad `.split` call is happening in the JSON deseralization process. 

If you could, are you able to use the hooks capability in the SDK to analyze the raw JSON response from the API and share that with us? https://github.com/EasyPost/easypost-python?tab=readme-ov-file#http-hooks

**Comment by austinhearn1** [comment]
@nwithan8 Hi, this issue is happening for all FedEx creates for the last 2 hours
Here is one of the tracking numbers: 415580123855

**Comment by nwithan8** [comment]
@austinhearn1 @kcharwood  I have confirmed with our internal engineers that there was a server-side bug causing bad JSON data to be returned, which in turn caused this issue. The bug has just been patched so this issue should resolved itself. I'm going to close this, but please let us know if you still face problems.

**Comment by kcharwood** [comment]
Good times. Appreciate the fast response @nwithan8 🍻

**Comment by kcharwood** [comment]
Just to be clear, still seeing the problem as of 2 minutes ago. Has that server side patch been deployed?

**Comment by maxlancaster** [comment]
Also seeing this problem as of 1 minute ago

**Comment by nwithan8** [comment]
Sorry, I misspoke. The patch is in the process of going out now.
