### ISSUE TITLE
Can't buy using rate_id

### ISSUE THREAD

**Issue by ssilverm** [EasyPost/easypost-python#36]
import easypost
easypost.api_key = "<YOUR_TEST/PRODUCTION_API_KEY>"

shipment = easypost.Shipment.retrieve("shp_...")
shipment.buy(rate="rate_...")

Goes to this URL with these params:
**/shipments/shp_.../buy
{'rate': 'rate_...'}**
and returns this error:
Error: A valid rate must be supplied in order to purchase a shipment. Please verify the rate exists and that the rate is associated with the shipment being purchased.

Using shipment.lowest_rate() **works** but only because it's returning the entire rate object as a param.

import easypost
easypost.api_key = "<YOUR_TEST/PRODUCTION_API_KEY>"

shipment = easypost.Shipment.retrieve("shp_...")
shipment.buy(rate=shipment.lowest_rate(), insurance=249.99)

**/shipments/shp_.../buy**
{'rate': <Rate Rate at 0x110f2f310> JSON: {
  "api_key": "API_KEY", 
  "carrier": "USPS", 
  "carrier_account_id": "ca_...", 
  "created_at": "2016-02-19T06:06:59Z", 
  "currency": "USD", 
  "delivery_date": null, 
etc....

So it seems theres a problem with the API not accepting just the rate_id, or the documentation is wrong.

**Comment by att14** [comment]
You have to specify a full Rate object or a dictionary representing a hash object.

```
shipment.buy(rate={"id": "rate_..."})
```

OR

```
shipment.buy(rate=shipment.rate[0])
```

**Comment by ssilverm** [comment]
Thanks!
