### ISSUE TITLE
`api_key` dumped / exposed in every `EasyPostObject`

### ISSUE THREAD

**Issue by fenginx** [EasyPost/easypost-python#39]
It simply makes no sense to include `api_key` in JSON dumps.  Went through the code base and surprisedly found the fact that security seems not to be a big deal for EasyPost devs.

**Comment by att14** [comment]
Try the latest commit and let me know if I broke anything.

**Comment by fenginx** [comment]
Ha!  Thanks for the quick update!  Will test now.
Actually I just patched lib with my own `sanitize_to_dict()` in my project, but upstream fix is always welcome!
👍

**Comment by fenginx** [comment]
All tests on my end passed (I didn't expect `api_key` in JSON so it does not break anything here).
Can't wait to pip install the new version!  Thanks a lot!

**Comment by fenginx** [comment]
Just checking - no PyPI release yet?

**Comment by victoryftw** [comment]
Sorry for the delay on this; we've just released the newest version on PyPi so you should be good to go now!
