### ISSUE TITLE
Can't use library with newest version of Requests module

### ISSUE THREAD

**Issue by MLublin** [EasyPost/easypost-python#47]
I'm using easypost version `3.1.1`. I had the newest version of the `requests` module installed (`2.12.4`) but all methods on the easypost library kept failing:

```/Library/Python/2.7/site-packages/easypost/__init__.pyc in requests_request(self, method, abs_url, headers, params)
    304             http_status = result.status_code
    305         except Exception as e:
--> 306             raise Error("Unexpected error communicating with EasyPost. If this "
    307                         "problem persists please let us know at contact@easypost.com.")
    308         return http_body, http_status
```
I eventually fixed the problem by reverting to an older version of the `requests` library (`2.7.0`) and then easypost worked again. Has anyone else encountered this?

**Comment by victoryftw** [comment]
I've not been able to reproduce this issue using Requests v2.12.14, which is, interestingly, also the version of Requests I've been using to develop this library. Could you provide a failing code sample so we can investigate further? Do you know if this same issue occurs with the newest version of the client library? Thanks!
