### ISSUE TITLE
Can't use `'key' in shipment`

### ISSUE THREAD

**Issue by skullydazed** [EasyPost/easypost-python#54]
Attempting to check if a shipment has a selected rate results in this error:

```
Traceback (most recent call last):
  File "sales_report.py", line 32, in <module>
    if 'selected_rate' in shipment:
  File "/usr/local/lib/python2.7/site-packages/easypost/__init__.py", line 405, in __getitem__
    return self.__dict__[k]
KeyError: 0
```

I'm not entirely sure why that is (and my time to look into this issue has run out for today, so I just caught the exception instead) but this should probably be supported behavior. Here's the code that triggers the bug, it happens when I retrieve a shipment that was created but postage hasn't been purchased for:

```
import easypost

easypost.api_key = 'my_key_text'

shipment = easypost.Shipment.retrieve(order['easypost_shipment_id'])
if 'selected_rate' in shipment:
    order['ship_date'] = shipment['selected_rate']['created_at']
```

**Comment by att14** [comment]
You should just use dot notation instead of treating `Shipment`s like a dictionary.

```python
if shipment.selected_rate:
  ...
```

Unfortunately the way this library was originally written it does things with `__dict__` and `__getitem__` that shouldn't be done. I would avoid treating any resource as a dictionary.
