### ISSUE TITLE
Error: The Pickup Location is a mandatory field

### ISSUE THREAD

**Issue by notatoad** [EasyPost/easypost-python#60]
I'm attempting to schedule a pickup for a batch with a test API key, and getting a "location is a mandatory field" error, however as far as i can tell "location" is not a field at all on a pickup.  The pickup object creates fine, error occurs when attempting to call `pickupObj.buy(carrier='Purolator', service='PurolatorPickup')`. 

pickup object looks like this (some info replaced with "XXX"):

[pickup.txt](https://github.com/EasyPost/easypost-python/files/1020649/pickup.txt)

`<Pickup b'Pickup' at 0x7f8ec3d59400> JSON: {
  "address": {
    "carrier_facility": null,
    "city": "Canmore",
    "company": null,
    "country": "CA",
    "created_at": "2017-05-20T23:34:35Z",
    "email": null,
    "federal_tax_id": null,
    "id": "adr_de8a3d4703be4da5917ec9394adf88fe",
    "mode": "test",
    "name": "XXX",
    "object": "Address",
    "phone": "XXX",
    "residential": null,
    "state": "AB",
    "state_tax_id": null,
    "street1": "XXX",
    "street2": null,
    "updated_at": "2017-05-20T23:34:35Z",
    "verifications": {},
    "zip": "XXX"
  },
  "carrier_accounts": [],
  "confirmation": null,
  "created_at": "2017-05-23T01:08:41Z",
  "id": "pickup_b903680e49774671a36ddcb3ab28a8f0",
  "instructions": null,
  "is_account_address": true,
  "max_datetime": "2017-05-23T23:00:00Z",
  "messages": [],
  "min_datetime": "2017-05-23T14:00:00Z",
  "mode": "test",
  "object": "Pickup",
  "pickup_rates": [
    {
      "carrier": "Purolator",
      "created_at": "2017-05-23T01:08:41Z",
      "currency": "CAD",
      "id": "pickuprate_52ca9de05d2a4359a75a907044b20043",
      "mode": "test",
      "object": "PickupRate",
      "pickup_id": "pickup_b903680e49774671a36ddcb3ab28a8f0",
      "rate": "0.00",
      "service": "PurolatorPickup",
      "updated_at": "2017-05-23T01:08:41Z"
    }
  ],
  "reference": null,
  "status": "unknown",
  "updated_at": "2017-05-23T01:08:41Z"
}`

easypost version is 3.6.0
python version 3.4.3

**Comment by mwaldt** [comment]
Since this is not a client library specific question I am marking this as closed, for support inquiries please write into support@easypost.com.
