### ISSUE TITLE
Unable to create pickup

### ISSUE THREAD

**Issue by packagepickup77** [EasyPost/easypost-python#65]
Unable to create pickup, the carrier associated with the batch shipments is inconsistent.

I'm using this code.

`

           try:
            to_address = easypost.Address.create(
                verify=["delivery"],
                name='Dr. Steve Brule',
                street1='179 N Harbor Dr',
                city='Redondo Beach',
                state='CA',
                zip='90277',
                country='US',
                phone='4153334444',
                email='dr_steve_brule@gmail.com'
            )

            from_address = easypost.Address.create(
                verify=["delivery"],
                street1="417 Montgomery Street",
                street2="FLOOR 5",
                city="San Francisco",
                state="CA",
                zip="94104",
                country="US",
                company="EasyPost",
                phone="415-456-7890"
            )

            new_address = easypost.Address.create(
                verify=["delivery"],
                street1="413835 N Northsight Blvd",
                city="Scottsdale",
                state="AZ",
                zip="85260",
                country="US",
                phone="416-446-7897"
            )

            new_address2 = {
                             "name": 'james smith',
                             "street1": '1413835 N Northsight Blvd',
                             "city": 'Scottsdale',
                             "state": 'AZ',
                             "zip": '85260',
                             "country": 'US',
                             "phone": '8744883682',
                             "email": 'dss@gmail.com'
                         }

            customs_item = easypost.CustomsItem.create(
                description="EasyPost t-shirts",
                hs_tariff_number=123456,
                origin_country="US",
                quantity=2,
                value=96.27,
                weight=21.1
            )
            customs_info = easypost.CustomsInfo.create(
                customs_certify=1,
                customs_signer="Hector Hammerfall",
                contents_type="gift",
                contents_explanation="",
                eel_pfc="NOEEI 30.37(a)",
                non_delivery_option="return",
                restriction_type="none",
                restriction_comments="",
                customs_items=[customs_item]
            )

            parcel = easypost.Parcel.create(
                length=20.2,
                width=10.9,
                height=5,
                weight=65.9
            )
            shipment = easypost.Shipment.create(
                to_address=to_address,
                from_address=from_address,
                parcel=parcel,
                customs_info=customs_info,
                carrier_accounts='ca_843506a2a61e485e94c6dfdab3e817df',

            )

            pickup = easypost.Pickup.create(
                address=new_address2,
                shipment=shipment,
                mode='test',
                carrier_accounts='ca_843506a2a61e485e94c6dfdab3e817df',
                reference="my-first-pickup",
                min_datetime="2017-07-21 10:30:00",
                max_datetime="2017-07-22 10:30:00",
                is_account_address=False,
                instructions="Special pickup instructions")

            carrier_accounts = easypost.CarrierAccount.all()

            return HttpResponse(pickup)

        except easypost.Error as e:

            return HttpResponse(e)`

**Comment by att14** [comment]
The shipment needs to be purchased in order to create a Pickup. Most carriers have some requirements around the service levels within the Pickup so in order for us to pass this information along the shipment either needs to be purchased or you need to use a batch to create the pickup. When using a batch to create the pickup you must set `carrier` and `service` on each batch shipment.
