### ISSUE TITLE
Can I Inherit AllResource and CreateResource for v1 API?

### ISSUE THREAD

**Issue by Congee** [EasyPost/easypost-python#70]
Hi, I have been given some v1 APIs from eastpost staff. Will everything blow up if I use this SDK for v1 API?

**Comment by mwaldt** [comment]
The v1 endpoints have been depreciated and should not be used at this time. You can find our latest documentation [here](https://www.easypost.com/docs/api/python.html). If you have any questions please reach out to support@easypost.com.
