### ISSUE TITLE
Support for multiple-package shipments?

### ISSUE THREAD

**Issue by zachgoldstein** [EasyPost/easypost-python#74]
I'm looking to have a single fedex shipment contain multiple packages, with a single master tracking code and shipping labels that indicate they're part of a multiple package shipment.

I see a bit of conflicting documentation about this. Here I see that easypost supports multi-package shipments: https://www.easypost.com/can-i-add-multiple-packages-to-a-fedex-shipment.

Here in the docs, https://www.easypost.com/docs/api#shipment-object, I see "The dimensions and weight of the package", which seems to imply that only a single parcel is supported.

So does easypost support this? How would I go about implementing that with this client library?

Thanks!

**Comment by zachgoldstein** [comment]
The PHP client lib seems to support this here: https://github.com/EasyPost/easypost-php/blob/master/examples/orders.php

**Comment by mwaldt** [comment]
Please write into support@easypost.com for questions like these. You will need to use our orders objects. You can find the documentation below.
https://www.easypost.com/docs/api/python#orders-create-codesample
