### ISSUE TITLE
Problem when creating a report by date

### ISSUE THREAD

**Issue by loglow** [EasyPost/easypost-python#79]
When creating a report, the start and end dates are ignored. The created report uses the current date instead. This is not a problem with the API since other client libraries seem to work fine.

I think the problem is related to this line:

https://github.com/EasyPost/easypost-python/blob/3115008d2adfd6139053b40918aa08e347fc905e/easypost/__init__.py#L966

Things appear to work properly when `wrapped_params` is changed to `params` like this:

`response, api_key = requestor.request('post', url, params, False)`

**Comment by Justintime50** [comment]
@jontsai this has been fixed with #91 and can be closed.

**Comment by jontsai** [comment]
Resolved with #91
