### ISSUE TITLE
Latest Version 3.6.4 Not Available on PyPi

### ISSUE THREAD

**Issue by david-revcascade** [EasyPost/easypost-python#81]
Only up to 3.6.3 available here:
https://pypi.org/project/easypost/

**Comment by Roguelazer** [comment]
There isn't actually a 3.6.4 yet, that's just a placeholder in the top of `CHANGELOG.md`. There will probably be a 3.6.4 once I get the current batch of fixes landed, and I will make sure to put it on PyPI.
