### ISSUE TITLE
Problem with shipment buy using lowest rate

### ISSUE THREAD

**Issue by catokx** [EasyPost/easypost-python#82]
Good morning, following the library guidelines i'm buyng the shipment with this line of code 

`shipment.buy(rate = shipment.lowest_rate())`

i have 2 problems with this since toda 9th July 2019,
1) the shipment selected is the highest rate (e.g. DHL Medical 35,65€)
2) i receive an error from the backend "ValueError: could not convert string to float: '35,65'"

Can you help me?

**Comment by pseudoben** [comment]
Hi, @catokx, which DHL carrier was this for (DHL Express, DHL Global Mail, DHL eCommerce, etc.)?

**Comment by catokx** [comment]
dhl express

Il giorno mar 9 lug 2019 alle 19:41 Ben Greenberg <notifications@github.com>
ha scritto:

**Comment by Roguelazer** [comment]
We're working on fixing this on the backend

**Comment by Roguelazer** [comment]
This was resolved in the backend on 2019-07-10; please let us know if you see any additional issues.
