### ISSUE TITLE
DeprecationWarning: Use of .. or absolute paths will raise exceptions...

### ISSUE THREAD

**Issue by Justintime50** [EasyPost/easypost-python#98]
When `PYTHONWARNINGS=always` is set, I get the following from the pkg_resources library:

```
/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py:1151: DeprecationWarning: 
Use of .. or absolute path in a resource path is not allowed and will raise exceptions in a future 
release.
  self, resource_name
```

We'll need to adjust the relative path to the `VERSION` file in the near future to avoid throwing exceptions on each call. The offending code is in `version.py`:

```python
VERSION_FILE = pkg_resources.resource_stream('easypost', '../VERSION')
```

**Comment by Roguelazer** [comment]
We probably just need to stop doing the stupid `VERSION` file trick and make the version a literal in `setup.py` and `__init__.py`. The only reason we didn't was because an earlier author of this project was strongly opposed to duplicating that single line.
